baseURL = 'https://vapb.github.io/vapb-blog/'
defaultContentLanguage = 'pt'
defaultContentLanguageInSubdir = false
languageCode = 'pt-br'
title = 'VAPB BLOG'
theme = 'vapb-theme'
paginate = 20

[pagination]
  pagerSize = 20

[languages]
  [languages.pt]
    contentDir = 'content/pt'
    languageName = 'Português'
    languageCode = 'pt-br'
    title = 'VAPB BLOG'
    weight = 2
    [languages.pt.params]
      subtitle = "Explorando Dados, Código e Curiosidades"
      introduction = "Parte blog técnico, parte despejo de ideias, este espaço é uma mistura de posts técnicos, showcases de projetos e notas aleatórias direto do meu cérebro"

[languages.pt.menu]
  [[languages.pt.menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "posts"
    weight = 10

  [[languages.pt.menu.main]]
    identifier = "about"
    name = "Sobre Mim"
    url = "about"
    weight = 100

  [[languages.pt.menu.main]]
    identifier = "estante"
    name = "Estante"
    url = "estante"
    weight = 20

  [[languages.pt.menu.main]]
    identifier = "projects"
    name = "Projetos"
    url = "projects"
    weight = 30
  
  [[languages.pt.menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "tags"
    weight = 40

[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2

  [markup.goldmark.renderer]
  unsafe= true 